### ISSUE TITLE
Issues installing in ubuntu 14.04

### ISSUE THREAD

**Issue by Zephyrante** [mefernandez/temply#7]
Need to be sudoer or root to use 
`npm start`

After launching command as sudo i get:

``` bash
http GET https://registry.npmjs.org/temply-express
npm http 404 https://registry.npmjs.org/temply-express
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-49-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/luis/dev/git/temply
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 304 https://registry.npmjs.org/http-perf/0.0.5
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/luis/dev/git/temply/npm-debug.log
npm ERR! not ok code 0

```

**Comment by mefernandez** [comment]
Básicamente el error dice que no encuentra la dependencia `temply-express`. Parece que `npm` la está buscando en https://registry.npmjs.org/temply-express, cuando en realidad `temply-express` está en local, dentro de `modules` (ver `package.json`).

Puede ser que la versión de `npm` esté anticuada; los módulos locales (los que en el `package.json` empiezan con `file:some/path`) están soportados desde `npm` versión `2.0.0` (ver https://docs.npmjs.com/files/package.json#local-paths)

En mis caso tengo instalada la versión de **npm 2.5.1**. 
@Zephyrante  Checkea tu versión de npm (`npm -v`).

**Comment by Zephyrante** [comment]
Wierd, i did update node and npm before doing this issue and it seems it didnt install latest versions.

After some work i managed to update npm.

Works like a charm now.

Thx
